# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-26 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='written_by',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
