# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-26 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0002_message_written_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='written_by',
            field=models.IntegerField(),
        ),
    ]
