# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-26 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0003_auto_20180526_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='written_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_wrote_messages', to='user_dashboard.User'),
        ),
    ]
